services:
  - type: web
    name: my-n8n-bot
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: https://github.com/n8nio/n8n.git#master
    dockerCommand: ./docker-entrypoint.sh
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
    domains:
      - n8n-bot.onrender.com
